-- Migration 006: Frete Form Enhancement
-- Adiciona campos detalhados ao formulário de frete

ALTER TABLE fretes ADD COLUMN IF NOT EXISTS cargo_species VARCHAR(50);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS product VARCHAR(255);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS onu_number VARCHAR(20);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS temperature DECIMAL(5,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS weight_unit VARCHAR(20) DEFAULT 'toneladas';
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS total_weight DECIMAL(10,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS volumes INTEGER;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS cubed_weight DECIMAL(10,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS cubic_meters DECIMAL(10,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS dimension_length DECIMAL(6,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS dimension_width DECIMAL(6,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS dimension_height DECIMAL(6,2);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS freight_type VARCHAR(20) DEFAULT 'completa';
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS occupancy_percentage INTEGER;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS body_types TEXT;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS requires_lona BOOLEAN DEFAULT FALSE;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS requires_tracker BOOLEAN DEFAULT FALSE;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS requires_insurance BOOLEAN DEFAULT FALSE;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS value_known BOOLEAN DEFAULT FALSE;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS price_calculation VARCHAR(20);
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS payment_methods TEXT;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS advance_percentage INTEGER;
ALTER TABLE fretes ADD COLUMN IF NOT EXISTS invoice_days INTEGER;
